//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zavodEntities : DbContext
    {
        public zavodEntities()
            : base("name=zavodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Зарплата> Зарплата { get; set; }
        public virtual DbSet<ИнвентаризацияТовара> ИнвентаризацияТовара { get; set; }
        public virtual DbSet<Паспорт> Паспорт { get; set; }
        public virtual DbSet<ПокупкаТовара> ПокупкаТовара { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<ПриемНаРаботу> ПриемНаРаботу { get; set; }
        public virtual DbSet<ПриемТовара> ПриемТовара { get; set; }
        public virtual DbSet<Продукт> Продукт { get; set; }
        public virtual DbSet<Производство> Производство { get; set; }
        public virtual DbSet<Расписание> Расписание { get; set; }
        public virtual DbSet<Расходники> Расходники { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<СписаниеТовара> СписаниеТовара { get; set; }
        public virtual DbSet<Увольнение> Увольнение { get; set; }
    }
}
