//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Зарплата
    {
        public long ID { get; set; }
        public long IDБухгалтера { get; set; }
        public long IDСотрудника { get; set; }
        public double Сумма { get; set; }
        public System.DateTime Дата { get; set; }
    }
}
