//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Паспорт
    {
        public long ID { get; set; }
        public string Номер { get; set; }
        public string Серия { get; set; }
        public string КемВыдан { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public bool Пол { get; set; }
    }
}
