//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public string Sname { get; set; }
        public string NumberPhone { get; set; }
        public long PassportID { get; set; }
        public string Медкнижка { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public long IDДолжности { get; set; }
    
        public virtual Должности Должности { get; set; }
    }
}
